#Kivy wants RGB values as float betweem 0 and 1, however
#My color picker software uses values from 0 to 255

RGB_DENOMINATOR = 255

DAY_LABEL_BG_COLOR = (205 / RGB_DENOMINATOR, 182 / RGB_DENOMINATOR, 184 / RGB_DENOMINATOR)  # hex cdb6b8
SCROLL_BUTTON_BG_COLOR = (124 / RGB_DENOMINATOR, 110 / RGB_DENOMINATOR, 110 / RGB_DENOMINATOR)  # hex 7c6e6e
CURRENT_MONTH_BG_COLOR = (169 / RGB_DENOMINATOR, 150 / RGB_DENOMINATOR, 151 / RGB_DENOMINATOR)  # hex a99697

LIGHTER_DAY_WIDGET_COLOR = ()
DARKER_DAY_WIDGET_COLOR = ()

