# Kivy wants RGB values as float between 0 and 1, however
# My color picker software uses values from 0 to 255

RGB_DIVISOR = 255

DAY_LABEL_BG_COLOR = (205 / RGB_DIVISOR, 182 / RGB_DIVISOR, 184 / RGB_DIVISOR)  # hex cdb6b8
SCROLL_BUTTON_BG_COLOR = (124 / RGB_DIVISOR, 110 / RGB_DIVISOR, 110 / RGB_DIVISOR)  # hex 7c6e6e
CURRENT_MONTH_BG_COLOR = (169 / RGB_DIVISOR, 150 / RGB_DIVISOR, 151 / RGB_DIVISOR)  # hex a99697

LIGHTER_DAY_WIDGET_COLOR = ()
DARKER_DAY_WIDGET_COLOR = ()
